$axure.loadCurrentPage({
  "url":"foto_2.html",
  "generationDate":new Date(1396311435846.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/home/bg.jpg",
    "width":150,
    "height":150},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"f4d706da5682419787ae95bded998e7c",
    "type":"Axure:Page",
    "name":"Foto 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a8fd449042e743fd823f45b44d5af60a",
          "label":"5",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":380,
              "y":776},
            "size":{
              "width":1080,
              "height":574},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09c8729a529945838afad875f2142ccc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":380,
                  "y":776},
                "size":{
                  "width":1080,
                  "height":574},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide 5 fade 500 ms",
                      "objectsToFades":[{
                          "objectPath":["a8fd449042e743fd823f45b44d5af60a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/foto_2/5_u0.jpg"}},
{
          "id":"45cd4efca0634780b2ef271e43e38cbf",
          "label":"4",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":370,
              "y":450},
            "size":{
              "width":990,
              "height":499},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"183e6922e5644de8b2bb4ffb91526fec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":370,
                  "y":450},
                "size":{
                  "width":990,
                  "height":499},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide 4 fade 500 ms",
                      "objectsToFades":[{
                          "objectPath":["45cd4efca0634780b2ef271e43e38cbf"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/foto_2/4_u2.jpg"}},
{
          "id":"1f33f06d57d84495ad73bdd7d3606919",
          "label":"3",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":380,
              "y":227},
            "size":{
              "width":1150,
              "height":583},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa2812589d714b87aad87e2f408f255a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":380,
                  "y":227},
                "size":{
                  "width":1150,
                  "height":583},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide 3 fade 500 ms",
                      "objectsToFades":[{
                          "objectPath":["1f33f06d57d84495ad73bdd7d3606919"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/foto_2/3_u4.jpg"}},
{
          "id":"b37c477073e34ace951478d9fd4ae9b8",
          "label":"2",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":370,
              "y":227},
            "size":{
              "width":1010,
              "height":525},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87b5c41c4a724d6085618f6706f1b6b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":370,
                  "y":227},
                "size":{
                  "width":1010,
                  "height":525},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide 2 fade 500 ms",
                      "objectsToFades":[{
                          "objectPath":["b37c477073e34ace951478d9fd4ae9b8"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/foto_2/2_u6.jpg"}},
{
          "id":"0eebadd2233c4f9b83a9ef42fea571e3",
          "label":"1",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":380,
              "y":227},
            "size":{
              "width":910,
              "height":623},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d26d166521c44bab48f929baaa01e66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":380,
                  "y":227},
                "size":{
                  "width":910,
                  "height":623},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide 1 fade 500 ms",
                      "objectsToFades":[{
                          "objectPath":["0eebadd2233c4f9b83a9ef42fea571e3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/foto_2/1_u8.jpg"}},
{
          "id":"b897f144b48d428a8e9d23845cc519bf",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"d59745e0967344388c74df2caf886644"},
{
          "id":"586d9d28ccae43c29680cffddc393192",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":1480}},
          "adaptiveStyles":{
},
          "masterId":"8df23209c40a4fc9b457cf864110f3ea"},
{
          "id":"81b4f5064ff34e7eac1fd124d1a2e32b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":189,
              "y":280}},
          "adaptiveStyles":{
},
          "masterId":"10e383d496e34104bdb52748888f77bd"},
{
          "id":"d396f895c2394e398a2799477038c35c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":180},
            "size":{
              "width":167,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc4fadee8bf1499690e91fe5a719eec9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":417,
                  "y":180},
                "size":{
                  "width":167,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de8cf6ff426e4d079982270de74f045b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":428,
              "y":280},
            "size":{
              "width":282,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81a10cd23be3428fbcf1705787caf2ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":428,
                  "y":280},
                "size":{
                  "width":282,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show 1 treat as lightbox",
                      "objectsToFades":[{
                          "objectPath":["0eebadd2233c4f9b83a9ef42fea571e3"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"lightbox",
                              "lightbox":{
                                "r":255,
                                "g":204,
                                "b":102,
                                "a":155}}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/foto_2/1_u8.jpg"}},
{
          "id":"5ad4b3428dcc46fbb16038c7548c1b6b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":280},
            "size":{
              "width":375,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38d83d238338431c830e8014020e5c63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":760,
                  "y":280},
                "size":{
                  "width":375,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show 2 treat as lightbox",
                      "objectsToFades":[{
                          "objectPath":["b37c477073e34ace951478d9fd4ae9b8"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"lightbox",
                              "lightbox":{
                                "r":255,
                                "g":204,
                                "b":102,
                                "a":155}}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/foto_2/2_u6.jpg"}},
{
          "id":"87e7aab9db4f41cd8f2613f8ed363ea3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":472},
            "size":{
              "width":620,
              "height":248}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab5140c7c3f349d484a776ec2ca8e7bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":472},
                "size":{
                  "width":620,
                  "height":248}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show 3 treat as lightbox",
                      "objectsToFades":[{
                          "objectPath":["1f33f06d57d84495ad73bdd7d3606919"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"lightbox",
                              "lightbox":{
                                "r":255,
                                "g":204,
                                "b":102,
                                "a":155}}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/foto_2/3_u4.jpg"}},
{
          "id":"0699f5018bbe4a769190627a97cc1235",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":747},
            "size":{
              "width":620,
              "height":233}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1029a40f2154acea53ca207ac9b9347",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":747},
                "size":{
                  "width":620,
                  "height":233}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show 4 treat as lightbox",
                      "objectsToFades":[{
                          "objectPath":["45cd4efca0634780b2ef271e43e38cbf"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"lightbox",
                              "lightbox":{
                                "r":255,
                                "g":204,
                                "b":102,
                                "a":155}}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/foto_2/4_u2.jpg"}},
{
          "id":"1d995dc710354183a2d4cffa213f1695",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":1006},
            "size":{
              "width":620,
              "height":214}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5120219a8f594e78b3dd4f24513acd85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":1006},
                "size":{
                  "width":620,
                  "height":214}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show 5 treat as lightbox",
                      "objectsToFades":[{
                          "objectPath":["a8fd449042e743fd823f45b44d5af60a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"lightbox",
                              "lightbox":{
                                "r":255,
                                "g":204,
                                "b":102,
                                "a":155}}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/foto_2/5_u0.jpg"}}]}},
  "masters":{
    "d59745e0967344388c74df2caf886644":{
      "packageId":"d59745e0967344388c74df2caf886644",
      "type":"Axure:Master",
      "name":"Header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f6c449300b2e42b29dcedda54cc92693",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFFFFF66},
{
                    "color":0xFFFFFF00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFF9900},
{
                    "color":0xFFFF9900}]},
              "size":{
                "width":1000,
                "height":150},
              "cornerRadiusTopLeft":"20",
              "outerShadow":{
                "on":true,
                "offsetX":5,
                "offsetY":5,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f7f2d7888b5b42618ab4d834dc08a31f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFFFFF66},
{
                        "color":0xFFFFFF00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFF9900},
{
                        "color":0xFFFF9900}]},
                  "size":{
                    "width":1000,
                    "height":150},
                  "cornerRadiusTopLeft":"20",
                  "outerShadow":{
                    "on":true,
                    "offsetX":5,
                    "offsetY":5,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"26b6f37dbca141d993ce9c536b796593",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":235,
                "y":30},
              "size":{
                "width":183,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"65c65ba5f376424eb5737abe25040435",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":235,
                    "y":30},
                  "size":{
                    "width":183,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Info_about_Kreml in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"info_about_kreml.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e2fcb84e847d4b2286caa242488be952",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":466,
                "y":66},
              "size":{
                "width":183,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f11d7142a45949b38dd3b4a49750f4b6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":466,
                    "y":66},
                  "size":{
                    "width":183,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Zastroyka_territirii in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"zastroyka_territirii.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f2948da5f5034e9499c6a9f1a75aa448",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":700,
                "y":101},
              "size":{
                "width":103,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92578c3a504440769a54f851b946b2c6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":700,
                    "y":101},
                  "size":{
                    "width":103,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Foto in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"foto.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6825d988ecd44736a1010a2b986d259d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF515151,
                "opacity":1},
              "location":{
                "x":721,
                "y":10},
              "size":{
                "width":249,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"113a991ff79147139c9ce999f5c5cd13",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF515151,
                    "opacity":1},
                  "location":{
                    "x":721,
                    "y":10},
                  "size":{
                    "width":249,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show Svyas s razrab slide right 500 ms treat as lightbox",
                        "objectsToFades":[{
                            "objectPath":["5dc439b92a48420d9e73efdabbe37784"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "easing":"slideRight",
                                "duration":500,
                                "showType":"lightbox",
                                "lightbox":{
                                  "r":161,
                                  "g":161,
                                  "b":161,
                                  "a":155}}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5dc439b92a48420d9e73efdabbe37784",
            "label":"Svyas s razrab",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":350,
                "y":190},
              "size":{
                "width":440,
                "height":320},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"cd26c9cb2d9c4e09a2293d0a0a48ef2d",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"b829a9fad56f466d96d30991fbb20a8c",
                    "label":"",
                    "parentDynamicPanel":"5dc439b92a48420d9e73efdabbe37784",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"linearGradient",
                        "colors":[{
                            "color":0xFF66FFFF},
{
                            "color":0xFF66FFFF},
{
                            "color":0xFF66FF99},
{
                            "color":0xFF66FF33},
{
                            "color":0xFF00CC00},
{
                            "color":0xFF33CCFF},
{
                            "color":0xFF3399FF},
{
                            "color":0xFF6666FF},
{
                            "color":0xFFCCFF00},
{
                            "color":0xFFCCFF00}]},
                      "location":{
                        "x":-5,
                        "y":10},
                      "size":{
                        "width":420,
                        "height":310},
                      "borderWidth":"-1",
                      "cornerRadiusTopLeft":"80"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"944645ba26ea435d81d25f48057df3bc",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5dc439b92a48420d9e73efdabbe37784",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"linearGradient",
                            "colors":[{
                                "color":0xFF66FFFF},
{
                                "color":0xFF66FFFF},
{
                                "color":0xFF66FF99},
{
                                "color":0xFF66FF33},
{
                                "color":0xFF00CC00},
{
                                "color":0xFF33CCFF},
{
                                "color":0xFF3399FF},
{
                                "color":0xFF6666FF},
{
                                "color":0xFFCCFF00},
{
                                "color":0xFFCCFF00}]},
                          "location":{
                            "x":-5,
                            "y":10},
                          "size":{
                            "width":420,
                            "height":310},
                          "borderWidth":"-1",
                          "cornerRadiusTopLeft":"80"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u14.png"}},
{
                    "id":"0d9c0bc879974a80af39cb1c5b77cb54",
                    "label":"",
                    "parentDynamicPanel":"5dc439b92a48420d9e73efdabbe37784",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Полужирный', 'Arial'",
                      "fontSize":"20px",
                      "fontWeight":"700",
                      "location":{
                        "x":48,
                        "y":28},
                      "size":{
                        "width":218,
                        "height":24}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d6c722b661a74a909b271074a6a1ac5c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5dc439b92a48420d9e73efdabbe37784",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Полужирный', 'Arial'",
                          "fontSize":"20px",
                          "fontWeight":"700",
                          "location":{
                            "x":48,
                            "y":28},
                          "size":{
                            "width":218,
                            "height":24}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"7b8c3c67d59b45699e5e39323e32cdae",
                    "label":"",
                    "parentDynamicPanel":"5dc439b92a48420d9e73efdabbe37784",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Vineta BT Oblique', 'Vineta BT'",
                      "fontSize":"14px",
                      "fontStyle":"oblique",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0x6699CC},
                      "location":{
                        "x":30,
                        "y":70},
                      "size":{
                        "width":210,
                        "height":30},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFF006666},
                      "outerShadow":{
                        "on":false,
                        "offsetX":5,
                        "offsetY":5,
                        "blurRadius":5,
                        "color":{
                          "r":102,
                          "g":0,
                          "b":153,
                          "a":0.349019607843137}}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"70f93b1a6571498d9a4092a313a17a05",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5dc439b92a48420d9e73efdabbe37784",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Vineta BT Oblique', 'Vineta BT'",
                          "fontSize":"14px",
                          "fontStyle":"oblique",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF000000,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0x6699CC},
                          "location":{
                            "x":30,
                            "y":70},
                          "size":{
                            "width":210,
                            "height":30},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF006666},
                          "outerShadow":{
                            "on":false,
                            "offsetX":5,
                            "offsetY":5,
                            "blurRadius":5,
                            "color":{
                              "r":102,
                              "g":0,
                              "b":153,
                              "a":0.349019607843137}}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"0e6e4a8fb0a24596810ba309079679ea",
                    "label":"",
                    "parentDynamicPanel":"5dc439b92a48420d9e73efdabbe37784",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Showcard Gothic Обычный', 'Showcard Gothic'",
                      "horizontalAlignment":"left",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xA1A1A1},
                      "location":{
                        "x":30,
                        "y":186},
                      "size":{
                        "width":210,
                        "height":70},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0x797979}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d487fbb893514e90980b6ea78016fea1",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5dc439b92a48420d9e73efdabbe37784",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Showcard Gothic Обычный', 'Showcard Gothic'",
                          "horizontalAlignment":"left",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF000000,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xA1A1A1},
                          "location":{
                            "x":30,
                            "y":186},
                          "size":{
                            "width":210,
                            "height":70},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0x797979}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"014fe5c4ad7643a39608072c7ac45436",
                    "label":"",
                    "parentDynamicPanel":"5dc439b92a48420d9e73efdabbe37784",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Полужирный', 'Arial'",
                      "fontSize":"20px",
                      "fontWeight":"700",
                      "location":{
                        "x":48,
                        "y":140},
                      "size":{
                        "width":147,
                        "height":24}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0a364a738ab142d49c468d8b677b2500",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5dc439b92a48420d9e73efdabbe37784",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Полужирный', 'Arial'",
                          "fontSize":"20px",
                          "fontWeight":"700",
                          "location":{
                            "x":48,
                            "y":140},
                          "size":{
                            "width":147,
                            "height":24}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"3e289ef585604604b9f87a846a09bdd1",
                    "label":"",
                    "parentDynamicPanel":"5dc439b92a48420d9e73efdabbe37784",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":250,
                        "y":186},
                      "size":{
                        "width":30,
                        "height":24},
                      "cornerRadiusTopLeft":"15"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b8e0fbe1276543429d8d2ffd4328a99a",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5dc439b92a48420d9e73efdabbe37784",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":250,
                            "y":186},
                          "size":{
                            "width":30,
                            "height":24},
                          "cornerRadiusTopLeft":"15"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open http://www.mail.ru in New Window/Tab",
                                "target":{
                                  "targetType":"webUrl",
                                  "urlLiteral":{
                                    "exprType":"stringLiteral",
                                    "value":"http://www.mail.ru",
                                    "stos":[]},
                                  "includeVariables":false},
                                "linkType":"new"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u24.png"}},
{
                    "id":"3c3cd3ae561d41bcbdad0ba5d6aedaaa",
                    "label":"",
                    "parentDynamicPanel":"5dc439b92a48420d9e73efdabbe37784",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":250,
                        "y":225},
                      "size":{
                        "width":30,
                        "height":26},
                      "cornerRadiusTopLeft":"15"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"aee0f9b85b5f4870a8cb8d9f6f242bb1",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5dc439b92a48420d9e73efdabbe37784",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":250,
                            "y":225},
                          "size":{
                            "width":30,
                            "height":26},
                          "cornerRadiusTopLeft":"15"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open http://www.google.com in New Window/Tab",
                                "target":{
                                  "targetType":"webUrl",
                                  "urlLiteral":{
                                    "exprType":"stringLiteral",
                                    "value":"http://www.google.com",
                                    "stos":[]},
                                  "includeVariables":false},
                                "linkType":"new"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u26.png"}},
{
                    "id":"99976f6aa52c4f15ad491547cd5f7bd0",
                    "label":"",
                    "parentDynamicPanel":"5dc439b92a48420d9e73efdabbe37784",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":375,
                        "y":10},
                      "size":{
                        "width":40,
                        "height":42}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"4f3e40bac8c4460da1fe632c2986623f",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5dc439b92a48420d9e73efdabbe37784",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":375,
                            "y":10},
                          "size":{
                            "width":40,
                            "height":42}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"fadeWidget",
                                "description":"Hide Svyas s razrab slide left 500 ms",
                                "objectsToFades":[{
                                    "objectPath":["5dc439b92a48420d9e73efdabbe37784"],
                                    "fadeInfo":{
                                      "fadeType":"hide",
                                      "options":{
                                        "easing":"slideLeft",
                                        "duration":500,
                                        "showType":"none"}}}]}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u28.png"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"6b3cd8b6d9324d6bb12a83271bf92ab9",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":40,
                "y":30},
              "size":{
                "width":120,
                "height":100},
              "cornerRadiusTopLeft":"54"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d8373288b7304f0a9888286676dd3221",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":40,
                    "y":30},
                  "size":{
                    "width":120,
                    "height":100},
                  "cornerRadiusTopLeft":"54"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u30.png"}}]}},
    "8df23209c40a4fc9b457cf864110f3ea":{
      "packageId":"8df23209c40a4fc9b457cf864110f3ea",
      "type":"Axure:Master",
      "name":"Footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"bb7f5101b25549b0abe021e07cf74454",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFF9900FF},
{
                    "color":0xFF9900FF},
{
                    "color":0xFF660099},
{
                    "color":0xFF993366},
{
                    "color":0xFF990033},
{
                    "color":0xFF660033},
{
                    "color":0xFF660033}]},
              "location":{
                "x":240,
                "y":250},
              "size":{
                "width":1000,
                "height":150},
              "cornerRadiusTopLeft":"20"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"99647244f9dc477b97854a7c965bdc76",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFF9900FF},
{
                        "color":0xFF9900FF},
{
                        "color":0xFF660099},
{
                        "color":0xFF993366},
{
                        "color":0xFF990033},
{
                        "color":0xFF660033},
{
                        "color":0xFF660033}]},
                  "location":{
                    "x":240,
                    "y":250},
                  "size":{
                    "width":1000,
                    "height":150},
                  "cornerRadiusTopLeft":"20"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"68b12ee21b964ab58b79602439440bbf",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Cooper Black Oblique', 'Cooper'",
              "fontSize":"16px",
              "fontStyle":"oblique",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":260,
                "y":270},
              "size":{
                "width":159,
                "height":38}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"35bb1f59658840b385268fa95b358427",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Cooper Black Oblique', 'Cooper'",
                  "fontSize":"16px",
                  "fontStyle":"oblique",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":260,
                    "y":270},
                  "size":{
                    "width":159,
                    "height":38}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b9e1b7e2427046dabaa52ea823f07bd8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Harlow Solid SemiExpanded Italic Bold', 'Harlow Solid'",
              "fontSize":"14px",
              "fontWeight":"700",
              "fontStyle":"italic",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":1080,
                "y":274},
              "size":{
                "width":160,
                "height":102}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"443c05528a0942078bf81fea7f57625c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Harlow Solid SemiExpanded Italic Bold', 'Harlow Solid'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "fontStyle":"italic",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":1080,
                    "y":274},
                  "size":{
                    "width":160,
                    "height":102}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f22b5216f5c04105b0126db0aef73035",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":260,
                "y":330},
              "size":{
                "width":158,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"78eba64b07e24d22874732e21133eeb6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":260,
                    "y":330},
                  "size":{
                    "width":158,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"af1e2908adf846738eb54eff85f89b39",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":260,
                "y":357},
              "size":{
                "width":200,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"91adbd603caf4437872a0d5d6597432d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xA0A1A1A1,
                "opacity":0.627451002597809},
              "location":{
                "x":470,
                "y":350},
              "size":{
                "width":32,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cc88738b363442989449dc192d9aedef",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xA0A1A1A1,
                    "opacity":0.627451002597809},
                  "location":{
                    "x":470,
                    "y":350},
                  "size":{
                    "width":32,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Rassilka_sucseed in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"rassilka_sucseed.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u42.png"}}]}},
    "10e383d496e34104bdb52748888f77bd":{
      "packageId":"10e383d496e34104bdb52748888f77bd",
      "type":"Axure:Master",
      "name":"F&V_navigate",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a2b5ef8f1596478aafe7a988b8c390fb",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFF00CCFF},
{
                    "color":0xFF00CCFF},
{
                    "color":0xFF0066FF},
{
                    "color":0xFF0033CC},
{
                    "color":0xFF000066},
{
                    "color":0xFF000066}]},
              "location":{
                "x":180,
                "y":180},
              "size":{
                "width":210,
                "height":110},
              "cornerRadiusTopLeft":"10"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e4ee976b05814af3917555267acc4f27",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFF00CCFF},
{
                        "color":0xFF00CCFF},
{
                        "color":0xFF0066FF},
{
                        "color":0xFF0033CC},
{
                        "color":0xFF000066},
{
                        "color":0xFF000066}]},
                  "location":{
                    "x":180,
                    "y":180},
                  "size":{
                    "width":210,
                    "height":110},
                  "cornerRadiusTopLeft":"10"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/galery_of_foto/u45.png"}},
{
            "id":"e66f3d81e0ba4d258128861edc45d3fd",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFF00,
                "opacity":1},
              "location":{
                "x":192,
                "y":224},
              "size":{
                "width":186,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f387bc98fa784652b23ecbaded0f71c1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF00,
                    "opacity":1},
                  "location":{
                    "x":192,
                    "y":224},
                  "size":{
                    "width":186,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Galery of Foto in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"galery_of_foto.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "a8fd449042e743fd823f45b44d5af60a":{
      "scriptId":"u0"},
    "09c8729a529945838afad875f2142ccc":{
      "scriptId":"u1"},
    "45cd4efca0634780b2ef271e43e38cbf":{
      "scriptId":"u2"},
    "183e6922e5644de8b2bb4ffb91526fec":{
      "scriptId":"u3"},
    "1f33f06d57d84495ad73bdd7d3606919":{
      "scriptId":"u4"},
    "aa2812589d714b87aad87e2f408f255a":{
      "scriptId":"u5"},
    "b37c477073e34ace951478d9fd4ae9b8":{
      "scriptId":"u6"},
    "87b5c41c4a724d6085618f6706f1b6b6":{
      "scriptId":"u7"},
    "0eebadd2233c4f9b83a9ef42fea571e3":{
      "scriptId":"u8"},
    "2d26d166521c44bab48f929baaa01e66":{
      "scriptId":"u9"},
    "b897f144b48d428a8e9d23845cc519bf":{
      "scriptId":"u10",
      "f6c449300b2e42b29dcedda54cc92693":{
        "scriptId":"u11"},
      "f7f2d7888b5b42618ab4d834dc08a31f":{
        "scriptId":"u12"},
      "26b6f37dbca141d993ce9c536b796593":{
        "scriptId":"u13"},
      "65c65ba5f376424eb5737abe25040435":{
        "scriptId":"u14"},
      "e2fcb84e847d4b2286caa242488be952":{
        "scriptId":"u15"},
      "f11d7142a45949b38dd3b4a49750f4b6":{
        "scriptId":"u16"},
      "f2948da5f5034e9499c6a9f1a75aa448":{
        "scriptId":"u17"},
      "92578c3a504440769a54f851b946b2c6":{
        "scriptId":"u18"},
      "6825d988ecd44736a1010a2b986d259d":{
        "scriptId":"u19"},
      "113a991ff79147139c9ce999f5c5cd13":{
        "scriptId":"u20"},
      "5dc439b92a48420d9e73efdabbe37784":{
        "scriptId":"u21"},
      "b829a9fad56f466d96d30991fbb20a8c":{
        "scriptId":"u22"},
      "944645ba26ea435d81d25f48057df3bc":{
        "scriptId":"u23"},
      "0d9c0bc879974a80af39cb1c5b77cb54":{
        "scriptId":"u24"},
      "d6c722b661a74a909b271074a6a1ac5c":{
        "scriptId":"u25"},
      "7b8c3c67d59b45699e5e39323e32cdae":{
        "scriptId":"u26"},
      "70f93b1a6571498d9a4092a313a17a05":{
        "scriptId":"u27"},
      "0e6e4a8fb0a24596810ba309079679ea":{
        "scriptId":"u28"},
      "d487fbb893514e90980b6ea78016fea1":{
        "scriptId":"u29"},
      "014fe5c4ad7643a39608072c7ac45436":{
        "scriptId":"u30"},
      "0a364a738ab142d49c468d8b677b2500":{
        "scriptId":"u31"},
      "3e289ef585604604b9f87a846a09bdd1":{
        "scriptId":"u32"},
      "b8e0fbe1276543429d8d2ffd4328a99a":{
        "scriptId":"u33"},
      "3c3cd3ae561d41bcbdad0ba5d6aedaaa":{
        "scriptId":"u34"},
      "aee0f9b85b5f4870a8cb8d9f6f242bb1":{
        "scriptId":"u35"},
      "99976f6aa52c4f15ad491547cd5f7bd0":{
        "scriptId":"u36"},
      "4f3e40bac8c4460da1fe632c2986623f":{
        "scriptId":"u37"},
      "6b3cd8b6d9324d6bb12a83271bf92ab9":{
        "scriptId":"u38"},
      "d8373288b7304f0a9888286676dd3221":{
        "scriptId":"u39"}},
    "586d9d28ccae43c29680cffddc393192":{
      "scriptId":"u40",
      "bb7f5101b25549b0abe021e07cf74454":{
        "scriptId":"u41"},
      "99647244f9dc477b97854a7c965bdc76":{
        "scriptId":"u42"},
      "68b12ee21b964ab58b79602439440bbf":{
        "scriptId":"u43"},
      "35bb1f59658840b385268fa95b358427":{
        "scriptId":"u44"},
      "b9e1b7e2427046dabaa52ea823f07bd8":{
        "scriptId":"u45"},
      "443c05528a0942078bf81fea7f57625c":{
        "scriptId":"u46"},
      "f22b5216f5c04105b0126db0aef73035":{
        "scriptId":"u47"},
      "78eba64b07e24d22874732e21133eeb6":{
        "scriptId":"u48"},
      "af1e2908adf846738eb54eff85f89b39":{
        "scriptId":"u49"},
      "91adbd603caf4437872a0d5d6597432d":{
        "scriptId":"u50"},
      "cc88738b363442989449dc192d9aedef":{
        "scriptId":"u51"}},
    "81b4f5064ff34e7eac1fd124d1a2e32b":{
      "scriptId":"u52",
      "a2b5ef8f1596478aafe7a988b8c390fb":{
        "scriptId":"u53"},
      "e4ee976b05814af3917555267acc4f27":{
        "scriptId":"u54"},
      "e66f3d81e0ba4d258128861edc45d3fd":{
        "scriptId":"u55"},
      "f387bc98fa784652b23ecbaded0f71c1":{
        "scriptId":"u56"}},
    "d396f895c2394e398a2799477038c35c":{
      "scriptId":"u57"},
    "cc4fadee8bf1499690e91fe5a719eec9":{
      "scriptId":"u58"},
    "de8cf6ff426e4d079982270de74f045b":{
      "scriptId":"u59"},
    "81a10cd23be3428fbcf1705787caf2ec":{
      "scriptId":"u60"},
    "5ad4b3428dcc46fbb16038c7548c1b6b":{
      "scriptId":"u61"},
    "38d83d238338431c830e8014020e5c63":{
      "scriptId":"u62"},
    "87e7aab9db4f41cd8f2613f8ed363ea3":{
      "scriptId":"u63"},
    "ab5140c7c3f349d484a776ec2ca8e7bf":{
      "scriptId":"u64"},
    "0699f5018bbe4a769190627a97cc1235":{
      "scriptId":"u65"},
    "e1029a40f2154acea53ca207ac9b9347":{
      "scriptId":"u66"},
    "1d995dc710354183a2d4cffa213f1695":{
      "scriptId":"u67"},
    "5120219a8f594e78b3dd4f24513acd85":{
      "scriptId":"u68"}}});